[package]
name = "async_fuser"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.11.0"
err-report = "0.1.2"
libc = "0.2.183"
log = "0.4.29"
memchr = "2.8.0"
nix = { version = "0.31.2", features = ["fs", "user", "poll", "socket", "uio", "mount", "process", "ioctl"] }
num_enum = "0.7.5"
ref-cast = "1.0.25"
smallvec = "1.15.1"
tokio = { version = "1.50.0", features = ["fs", "io-util", "macros", "net", "process", "rt", "rt-multi-thread", "sync", "time"] }
zerocopy = { version = "0.8.42", features = ["derive"] }
serde = { version = "1.0.102", features = ["std", "derive"], optional = true }
async-trait = "0.1.89"
page_size = "0.6.0"
regex = "1.12.3"
xutex = { version = "0.2.1", features = ["std"] }
bimap = "0.6.3"
dashmap = "6.1.0"
lazy_static = "1.5.0"
# async_hybrid_fs = { git = "https://github.com/khanhtranngoccva/async_hybrid_fs", rev = "06d123b04d5195ce934b9de953086e0414ed760b", version = "0.1.0" }
async_hybrid_fs = { path = "../async_hybrid_fs", version = "0.1.0" }
instability = "0.3.12"
async-scoped = { version = "0.9.0", features = ["use-tokio"] }
futures = { version = "0.3.32", features = ["async-await"] }
tokio-util = "0.7.18"

[features]
default = []
macfuse-4-compat = []
serializable = ["serde"]
# Disable mount implementations. Code will compile but won't work.
# Can be used like this on Linux to check macOS code compiles:
# cargo check --target x86_64-apple-darwin --features=macos-no-mount
macos-no-mount = []

# Unstable features
unstable-lookup-backing = []

[dev-dependencies]
tempdir = "0.3.7"
test-log = "0.2.19"
